services:
    cleaning_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: cleaning_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - cleaning_redis
        networks:
            - cleaning_work_network

    cleaning_nginx:
        image: nginx:latest
        container_name: cleaning_nginx
        ports:
            - "8080:80"
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - cleaning_app
        networks:
            - cleaning_work_network

    cleaning_db:
        image: mysql:latest
        container_name: cleaning_db
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "cleaning_db_dev"
            MYSQL_USER: "cleaning_db_user"
            MYSQL_PASSWORD: "Dj3cj94K"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            - cleaning_work_network

    cleaning_redis:
        image: redis:latest
        container_name: cleaning_redis
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data

networks:
    cleaning_work_network:

volumes:
    redis_data:
    dbdata:
        driver: local

